require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MowgliBasket' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'MowgliBasketTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' }) # update this part
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'MowgliBasket-tvOS' do
  # Pods for MowgliBasket-tvOS

  target 'MowgliBasket-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
